name: Just check if it works

on:
  push:
    branches: [ master ]
    
jobs:
  build:
  
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java Env
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'apopt'
      
    - name: Build this with Maven
      run: mvn -B compile --file pom.xml
    
  
